import type { GithubAccount, GithubConnection, GithubDemoConnectResult, GithubRepo } from '../../../core/services/github.service'

const DEMO_ACCOUNT_ID = 'demo-github-account-001'
const now = () => new Date().toISOString()

const apiId = (slug: string) => `gh-repo-${slug}`

/** Catálogo local — misma forma que la API, visible sin conectar cuenta real */
export const CLIENT_DEMO_GITHUB_REPOS: GithubRepo[] = [
  {
    id: apiId('repo-cloudops-api'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'cloudops-api',
    fullName: 'cloudops-org/cloudops-api',
    description: 'API NestJS del control center',
    defaultBranch: 'main',
    language: 'TypeScript',
    stars: 42,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-cloudops-ui'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'cloudops-ui',
    fullName: 'cloudops-org/cloudops-ui',
    description: 'Frontend Angular 19',
    defaultBranch: 'main',
    language: 'TypeScript',
    stars: 38,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-infra'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'infra-terraform',
    fullName: 'cloudops-org/infra-terraform',
    description: 'Módulos Terraform AWS/GCP/Azure',
    defaultBranch: 'main',
    language: 'HCL',
    stars: 15,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-docs'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'cloudops-docs',
    fullName: 'cloudops-org/cloudops-docs',
    description: 'Documentación y runbooks',
    defaultBranch: 'main',
    language: 'Markdown',
    stars: 8,
    visibility: 'public',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-saas-worker'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'saas-worker',
    fullName: 'cloudops-org/saas-worker',
    description: 'Workers de colas y tareas programadas',
    defaultBranch: 'main',
    language: 'TypeScript',
    stars: 21,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-monitoring'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'monitoring-stack',
    fullName: 'cloudops-org/monitoring-stack',
    description: 'Prometheus, Grafana y alertas',
    defaultBranch: 'main',
    language: 'YAML',
    stars: 12,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-helm'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'helm-charts',
    fullName: 'cloudops-org/helm-charts',
    description: 'Charts Helm para despliegues K8s',
    defaultBranch: 'main',
    language: 'Smarty',
    stars: 9,
    visibility: 'public',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-auth-gateway'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'auth-gateway',
    fullName: 'cloudops-org/auth-gateway',
    description: 'Gateway OAuth2 / JWT para el SaaS',
    defaultBranch: 'develop',
    language: 'Go',
    stars: 27,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-ci-pipelines'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'ci-pipelines',
    fullName: 'cloudops-org/ci-pipelines',
    description: 'Pipelines GitHub Actions y reusable workflows',
    defaultBranch: 'main',
    language: 'YAML',
    stars: 18,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-mobile-app'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'mobile-app',
    fullName: 'cloudops-org/mobile-app',
    description: 'App móvil React Native — panel operaciones',
    defaultBranch: 'develop',
    language: 'TypeScript',
    stars: 14,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-edge-gateway'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'edge-gateway',
    fullName: 'cloudops-org/edge-gateway',
    description: 'API edge y rate limiting',
    defaultBranch: 'main',
    language: 'Rust',
    stars: 11,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
  {
    id: apiId('repo-data-lake'),
    accountId: DEMO_ACCOUNT_ID,
    name: 'data-lake',
    fullName: 'cloudops-org/data-lake',
    description: 'Ingesta y transformación de métricas cloud',
    defaultBranch: 'main',
    language: 'Python',
    stars: 6,
    visibility: 'private',
    updatedAt: now(),
    isDemo: true,
  },
]

export const CLIENT_DEMO_WEBHOOKS: Record<string, unknown>[] = [
  { id: 'gh-wh-1', repoFullName: 'cloudops-org/cloudops-api', event: 'push', url: 'https://hooks.cloudops.local/github/push', active: true },
  { id: 'gh-wh-2', repoFullName: 'cloudops-org/cloudops-ui', event: 'pull_request', url: 'https://hooks.cloudops.local/github/pr', active: true },
  { id: 'gh-wh-3', repoFullName: 'cloudops-org/saas-worker', event: 'workflow_run', url: 'https://hooks.cloudops.local/github/workflow', active: true },
  { id: 'gh-wh-4', repoFullName: 'cloudops-org/monitoring-stack', event: 'push', url: 'https://hooks.cloudops.local/github/monitoring', active: false },
]

export const CLIENT_DEMO_DEPLOYMENTS: Record<string, unknown>[] = [
  { id: 'gh-dep-1', repoFullName: 'cloudops-org/cloudops-api', branch: 'main', targetName: 'cluster-prod-01', targetType: 'kubernetes', status: 'success', createdAt: now() },
  { id: 'gh-dep-2', repoFullName: 'cloudops-org/cloudops-ui', branch: 'develop', targetName: 'vps-prod-nginx-01', targetType: 'vps', status: 'running', createdAt: now() },
  { id: 'gh-dep-3', repoFullName: 'cloudops-org/saas-worker', branch: 'main', targetName: 'docker-host-01', targetType: 'docker', status: 'success', createdAt: now() },
]

export const buildClientGithubDemoState = (): GithubDemoConnectResult => {
  const synced = CLIENT_DEMO_GITHUB_REPOS.length
  const account: GithubAccount = {
    id: DEMO_ACCOUNT_ID,
    label: 'GitHub Demo Account',
    username: 'cloudops-demo',
    organization: 'cloudops-lab',
    accountType: 'demo',
    accountTypeLabel: 'Demo',
    status: 'connected',
    statusLabel: 'Conectada',
    avatarUrl: 'https://github.com/cloudops-demo.png',
    lastValidatedAt: now(),
    lastSyncAt: now(),
    createdAt: now(),
    demoMode: true,
  }
  const connection: GithubConnection = {
    connected: true,
    username: 'cloudops-demo',
    avatarUrl: account.avatarUrl,
    connectedAt: account.createdAt,
    lastSyncAt: account.lastSyncAt,
    repoCount: synced,
    accountId: DEMO_ACCOUNT_ID,
    demoMode: true,
  }
  return {
    demoMode: true,
    account,
    connection,
    repos: CLIENT_DEMO_GITHUB_REPOS,
    synced,
    message: 'Vista demo — cuenta ya conectada con repositorios ficticios',
  }
}
