version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cloudops-postgres
    environment:
      POSTGRES_DB: cloudops
      POSTGRES_USER: cloudops
      POSTGRES_PASSWORD: cloudops_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudops -d cloudops"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: cloudops-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend-api:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.backend-api
    container_name: cloudops-backend
    environment:
      NODE_ENV: production
      API_PORT: 3000
      DEMO_MODE: "true"
      AUTO_DEMO_SEED: "true"
      DATABASE_URL: postgresql://cloudops:cloudops_dev_password@postgres:5432/cloudops
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change_me_in_production_use_long_random_string
      JWT_EXPIRES_IN: 1d
      CORS_ORIGIN: http://localhost:8080,http://127.0.0.1:8080,http://localhost:4200,http://127.0.0.1:4200
      ENCRYPTION_KEY: change_me_32_characters_minimum!!
      LOG_LEVEL: info
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.frontend-angular
    container_name: cloudops-frontend
    ports:
      - "8080:80"
    depends_on:
      backend-api:
        condition: service_healthy
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: cloudops-jenkins
    profiles: ["extras"]
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home

  vault:
    image: hashicorp/vault:1.15
    container_name: cloudops-vault
    profiles: ["extras"]
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK

  prometheus:
    image: prom/prometheus:latest
    container_name: cloudops-prometheus
    profiles: ["extras"]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  postgres_data:
  jenkins_data:
