export type SchedulerTaskType =
  | 'instance'
  | 'jenkins'
  | 'ssh'
  | 'backup'
  | 'sync'
  | 'report'
  | 'docker'
  | 'runbook'

export type SchedulerTaskStatus = 'running' | 'paused' | 'failed' | 'disabled' | 'pending'

export type SchedulerRunResult = 'success' | 'warning' | 'error' | 'skipped'

export interface SchedulerTask {
  id: string
  name: string
  description: string
  type: SchedulerTaskType
  cron: string
  cronHuman: string
  timezone: string
  target: string
  owner: string
  assignee: string
  nextRun: string
  nextRunAt: string
  lastRun: string
  lastRunAt: string
  lastResult: SchedulerRunResult
  status: SchedulerTaskStatus
  enabled: boolean
  retries: number
  maxDuration: string
  successRate: number
  runs7d: number
  failures7d: number
  tags: string[]
  linkedResource: string
  notifyOnFailure: boolean
  maintenanceWindow?: string
  command?: string
  parameters?: string
  concurrency?: number
  environment?: SchedulerEnvironment
  cloudProvider?: SchedulerCloudProvider
  priority?: SchedulerPriority
  credentialProfile?: string
  workingDirectory?: string
  notifyChannels?: string
  notifyOnSuccess?: boolean
  skipIfRunning?: boolean
  timeoutAction?: SchedulerTimeoutAction
  documentationUrl?: string
  executor?: string
  retryBackoff?: SchedulerRetryBackoff
}

export type SchedulerRetryBackoff = 'fixed' | 'linear' | 'exponential'

export type SchedulerEnvironment = 'production' | 'staging' | 'development'
export type SchedulerCloudProvider = 'aws' | 'gcp' | 'azure'
export type SchedulerPriority = 'low' | 'normal' | 'high' | 'critical'
export type SchedulerTimeoutAction = 'abort' | 'retry' | 'notify_only'

export interface SchedulerRunHistory {
  id: string
  taskId: string
  taskName: string
  type: SchedulerTaskType
  executedAt: string
  duration: string
  result: SchedulerRunResult
  triggeredBy: string
  output: string
}

export const SCHEDULER_TYPE_LABELS: Record<SchedulerTaskType, string> = {
  instance: 'Instancia cloud',
  jenkins: 'Jenkins',
  ssh: 'Comando SSH',
  backup: 'Backup',
  sync: 'Sincronización',
  report: 'Informe',
  docker: 'Docker',
  runbook: 'Runbook',
}

export const SCHEDULER_STATUS_LABELS: Record<SchedulerTaskStatus, string> = {
  running: 'Activa',
  paused: 'Pausada',
  failed: 'Con fallos',
  disabled: 'Deshabilitada',
  pending: 'Pendiente',
}

export const SCHEDULER_RESULT_LABELS: Record<SchedulerRunResult, string> = {
  success: 'Éxito',
  warning: 'Advertencia',
  error: 'Error',
  skipped: 'Omitida',
}

const ago = (mins: number): string => new Date(Date.now() - mins * 60_000).toISOString()
const ahead = (mins: number): string => new Date(Date.now() + mins * 60_000).toISOString()

export const defaultSchedulerTasks = (): SchedulerTask[] => [
  {
    id: 'sch-1',
    name: 'Apagar instancias staging',
    description: 'Detiene EC2 del entorno staging fuera del horario laboral para reducir coste.',
    type: 'instance',
    cron: '0 22 * * 1-5',
    cronHuman: 'Lun–Vie a las 22:00',
    timezone: 'Europe/Madrid',
    target: 'aws-staging-*',
    owner: 'FinOps',
    assignee: 'ops@cloudops.local',
    nextRun: 'Hoy 22:00',
    nextRunAt: ahead(180),
    lastRun: 'Ayer 22:01',
    lastRunAt: ago(1440),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 2,
    maxDuration: '15m',
    successRate: 98,
    runs7d: 5,
    failures7d: 0,
    tags: ['coste', 'staging', 'aws'],
    linkedResource: 'Cuenta AWS staging',
    notifyOnFailure: true,
    environment: 'staging',
    cloudProvider: 'aws',
  },
  {
    id: 'sch-2',
    name: 'Encender entorno desarrollo',
    description: 'Arranca instancias dev y valida health check HTTP antes de notificar al equipo.',
    type: 'instance',
    cron: '0 7 * * 1-5',
    cronHuman: 'Lun–Vie a las 07:00',
    timezone: 'Europe/Madrid',
    target: 'gcp-dev-vms',
    owner: 'Plataforma',
    assignee: 'dev-platform@cloudops.local',
    nextRun: 'Mañana 07:00',
    nextRunAt: ahead(600),
    lastRun: 'Hoy 07:02',
    lastRunAt: ago(960),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '20m',
    successRate: 100,
    runs7d: 5,
    failures7d: 0,
    tags: ['dev', 'gcp', 'morning'],
    linkedResource: 'Proyecto GCP dev-core',
    notifyOnFailure: false,
    environment: 'development',
    cloudProvider: 'gcp',
  },
  {
    id: 'sch-3',
    name: 'Tests integración nocturnos',
    description: 'Dispara job Jenkins deploy-staging-nightly con parámetros de rama develop.',
    type: 'jenkins',
    cron: '0 3 * * *',
    cronHuman: 'Todos los días a las 03:00',
    timezone: 'UTC',
    target: 'jenkins/deploy-staging-nightly',
    owner: 'CI/CD',
    assignee: 'ci@cloudops.local',
    nextRun: 'Mañana 03:00',
    nextRunAt: ahead(420),
    lastRun: 'Hoy 03:14',
    lastRunAt: ago(1200),
    lastResult: 'warning',
    status: 'running',
    enabled: true,
    retries: 0,
    maxDuration: '45m',
    successRate: 92,
    runs7d: 7,
    failures7d: 1,
    tags: ['jenkins', 'ci', 'nightly'],
    linkedResource: 'Job: deploy-staging-nightly',
    notifyOnFailure: true,
    maintenanceWindow: 'Dom 02:00–04:00 UTC',
    command: 'jenkins build deploy-staging-nightly',
    parameters: 'BRANCH=develop',
    concurrency: 1,
  },
  {
    id: 'sch-4',
    name: 'Limpieza disco SSH bastion',
    description: 'Ejecuta script de limpieza en bastion y VPS edge; rota logs mayores a 7 días.',
    type: 'ssh',
    cron: '0 4 * * 0',
    cronHuman: 'Domingos a las 04:00',
    timezone: 'Europe/Madrid',
    target: 'bastion-01, edge-fw-01',
    owner: 'SRE',
    assignee: 'ops@cloudops.local',
    nextRun: 'Dom 04:00',
    nextRunAt: ahead(2880),
    lastRun: 'Dom pasado 04:03',
    lastRunAt: ago(10080),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 3,
    maxDuration: '10m',
    successRate: 96,
    runs7d: 1,
    failures7d: 0,
    tags: ['ssh', 'mantenimiento', 'logs'],
    linkedResource: 'Inventario VPS',
    notifyOnFailure: true,
    command: '/opt/scripts/cleanup-disk.sh --days 7',
    parameters: 'HOSTS=bastion-01,edge-fw-01',
    concurrency: 2,
  },
  {
    id: 'sch-5',
    name: 'Backup diario AWS RDS',
    description: 'Snapshot automático + copia a bucket S3 con verificación de tamaño mínimo.',
    type: 'backup',
    cron: '0 2 * * *',
    cronHuman: 'Todos los días a las 02:00',
    timezone: 'Europe/Madrid',
    target: 'rds-prod-primary',
    owner: 'DBA',
    assignee: 'dba@cloudops.local',
    nextRun: 'Mañana 02:00',
    nextRunAt: ahead(360),
    lastRun: 'Hoy 02:08',
    lastRunAt: ago(1320),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 2,
    maxDuration: '35m',
    successRate: 99,
    runs7d: 7,
    failures7d: 0,
    tags: ['rds', 'backup', 'prod'],
    linkedResource: 'RDS prod-primary',
    notifyOnFailure: true,
  },
  {
    id: 'sch-6',
    name: 'Sync inventario GCP',
    description: 'Sincroniza VMs, discos y redes de todas las cuentas GCP vinculadas al catálogo.',
    type: 'sync',
    cron: '*/30 * * * *',
    cronHuman: 'Cada 30 minutos',
    timezone: 'UTC',
    target: 'all-gcp-projects',
    owner: 'Inventario',
    assignee: 'sync-bot@cloudops.local',
    nextRun: 'En 14 min',
    nextRunAt: ahead(14),
    lastRun: 'Hace 16 min',
    lastRunAt: ago(16),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '8m',
    successRate: 97,
    runs7d: 336,
    failures7d: 2,
    tags: ['gcp', 'inventory', 'sync'],
    linkedResource: '3 cuentas GCP',
    notifyOnFailure: false,
  },
  {
    id: 'sch-7',
    name: 'Informe costes semanal',
    description: 'Genera PDF de costes multi-cloud y envía a FinOps y dirección.',
    type: 'report',
    cron: '0 8 * * 1',
    cronHuman: 'Lunes a las 08:00',
    timezone: 'Europe/Madrid',
    target: 'cost-optimizer-module',
    owner: 'FinOps',
    assignee: 'finops@cloudops.local',
    nextRun: 'Lun 08:00',
    nextRunAt: ahead(4320),
    lastRun: 'Lun pasado 08:05',
    lastRunAt: ago(10080),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 0,
    maxDuration: '12m',
    successRate: 100,
    runs7d: 1,
    failures7d: 0,
    tags: ['coste', 'reporte', 'email'],
    linkedResource: 'Módulo Cost Optimizer',
    notifyOnFailure: true,
  },
  {
    id: 'sch-8',
    name: 'Prune imágenes Docker',
    description: 'Elimina imágenes dangling en hosts Docker del pool edge y monitoring.',
    type: 'docker',
    cron: '0 5 * * 0',
    cronHuman: 'Domingos a las 05:00',
    timezone: 'Europe/Madrid',
    target: 'docker-hosts-edge',
    owner: 'SRE',
    assignee: 'ops@cloudops.local',
    nextRun: 'Dom 05:00',
    nextRunAt: ahead(3000),
    lastRun: 'Dom pasado 05:00',
    lastRunAt: ago(10020),
    lastResult: 'error',
    status: 'failed',
    enabled: true,
    retries: 2,
    maxDuration: '25m',
    successRate: 88,
    runs7d: 1,
    failures7d: 1,
    tags: ['docker', 'cleanup'],
    linkedResource: '4 hosts Docker',
    notifyOnFailure: true,
  },
  {
    id: 'sch-9',
    name: 'Runbook backup PostgreSQL',
    description: 'Ejecuta runbook rb-pg-backup contra RDS staging como validación semanal.',
    type: 'runbook',
    cron: '0 6 * * 6',
    cronHuman: 'Sábados a las 06:00',
    timezone: 'Europe/Madrid',
    target: 'rds-staging-01',
    owner: 'DBA',
    assignee: 'scheduler@cloudops.local',
    nextRun: 'Sáb 06:00',
    nextRunAt: ahead(5760),
    lastRun: 'Sáb pasado 06:12',
    lastRunAt: ago(11520),
    lastResult: 'success',
    status: 'paused',
    enabled: false,
    retries: 1,
    maxDuration: '50m',
    successRate: 94,
    runs7d: 0,
    failures7d: 0,
    tags: ['runbook', 'postgres'],
    linkedResource: 'Runbook: Backup PostgreSQL',
    notifyOnFailure: true,
  },
  {
    id: 'sch-10',
    name: 'Reinicio rolling Nginx',
    description: 'Reload graceful en fleet Nginx producción tras ventana de mantenimiento.',
    type: 'instance',
    cron: '30 3 1 * *',
    cronHuman: 'Día 1 de cada mes 03:30',
    timezone: 'Europe/Madrid',
    target: 'nginx-fleet-prod',
    owner: 'Plataforma',
    assignee: 'ops@cloudops.local',
    nextRun: '01 Jul 03:30',
    nextRunAt: ahead(43200),
    lastRun: '01 Jun 03:31',
    lastRunAt: ago(43200),
    lastResult: 'success',
    status: 'pending',
    enabled: true,
    retries: 0,
    maxDuration: '30m',
    successRate: 100,
    runs7d: 0,
    failures7d: 0,
    tags: ['nginx', 'prod', 'maintenance'],
    linkedResource: 'ASG web-prod',
    notifyOnFailure: true,
    maintenanceWindow: '01:00–05:00 Europe/Madrid',
    command: 'nginx -s reload',
    parameters: 'FLEET=nginx-fleet-prod',
    concurrency: 3,
  },
  {
    id: 'sch-11',
    name: 'Rotación secretos Vault',
    description: 'Renueva tokens de aplicación en KV y sincroniza con Jenkins credentials store.',
    type: 'sync',
    cron: '0 */6 * * *',
    cronHuman: 'Cada 6 horas',
    timezone: 'UTC',
    target: 'vault-prod',
    owner: 'Seguridad',
    assignee: 'secops@cloudops.local',
    nextRun: 'En 2 h',
    nextRunAt: ahead(120),
    lastRun: 'Hoy 10:00',
    lastRunAt: ago(240),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '8m',
    successRate: 98,
    runs7d: 28,
    failures7d: 0,
    tags: ['vault', 'secrets'],
    linkedResource: 'Vault cluster prod',
    notifyOnFailure: true,
    command: 'vault rotate --path app/*',
    concurrency: 1,
  },
  {
    id: 'sch-12',
    name: 'Informe costes multi-cloud',
    description: 'Genera PDF y CSV de costes por cuenta y etiqueta para el equipo FinOps.',
    type: 'report',
    cron: '0 8 * * 1',
    cronHuman: 'Lunes a las 08:00',
    timezone: 'Europe/Madrid',
    target: 'billing-api',
    owner: 'FinOps',
    assignee: 'finops@cloudops.local',
    nextRun: 'Lun 08:00',
    nextRunAt: ahead(7200),
    lastRun: 'Lun pasado 08:05',
    lastRunAt: ago(10080),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 0,
    maxDuration: '15m',
    successRate: 100,
    runs7d: 1,
    failures7d: 0,
    tags: ['report', 'billing'],
    linkedResource: 'API Billing',
    notifyOnFailure: false,
    command: 'report:costs --format pdf,csv',
    parameters: 'RANGE=7d',
    concurrency: 1,
  },
  {
    id: 'sch-13',
    name: 'Health check load balancers',
    description: 'Comprueba backends activos y latencia p95 en todos los ALB/NLB de producción.',
    type: 'instance',
    cron: '*/15 * * * *',
    cronHuman: 'Cada 15 minutos',
    timezone: 'UTC',
    target: 'alb-prod-*',
    owner: 'SRE',
    assignee: 'ops@cloudops.local',
    nextRun: 'En 12 min',
    nextRunAt: ahead(12),
    lastRun: 'Hace 3 min',
    lastRunAt: ago(3),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 0,
    maxDuration: '5m',
    successRate: 99,
    runs7d: 672,
    failures7d: 2,
    tags: ['alb', 'health'],
    linkedResource: 'AWS ELB prod',
    notifyOnFailure: true,
    command: 'check-lb-health --threshold-p95 400ms',
    concurrency: 4,
  },
  {
    id: 'sch-14',
    name: 'Pipeline Terraform drift',
    description: 'Ejecuta terraform plan en workspaces críticos y abre issue si hay drift.',
    type: 'jenkins',
    cron: '0 5 * * 2',
    cronHuman: 'Martes a las 05:00',
    timezone: 'Europe/Madrid',
    target: 'jenkins-terraform',
    owner: 'IaC',
    assignee: 'iac@cloudops.local',
    nextRun: 'Mar 05:00',
    nextRunAt: ahead(8640),
    lastRun: 'Mar pasado 05:18',
    lastRunAt: ago(11520),
    lastResult: 'warning',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '90m',
    successRate: 91,
    runs7d: 1,
    failures7d: 0,
    tags: ['terraform', 'drift'],
    linkedResource: 'Job: tf-drift-scan',
    notifyOnFailure: true,
    command: 'jenkins build tf-drift-scan',
    parameters: 'WORKSPACES=prod,staging',
    concurrency: 2,
  },
  {
    id: 'sch-15',
    name: 'Snapshot volúmenes EBS staging',
    description: 'Snapshots incrementales de volúmenes adjuntos a instancias staging antes del fin de semana.',
    type: 'backup',
    cron: '0 23 * * 5',
    cronHuman: 'Viernes a las 23:00',
    timezone: 'Europe/Madrid',
    target: 'ebs-staging',
    owner: 'SRE',
    assignee: 'ops@cloudops.local',
    nextRun: 'Vie 23:00',
    nextRunAt: ahead(5400),
    lastRun: 'Vie pasado 23:04',
    lastRunAt: ago(11520),
    lastResult: 'success',
    status: 'paused',
    enabled: false,
    retries: 2,
    maxDuration: '40m',
    successRate: 97,
    runs7d: 0,
    failures7d: 0,
    tags: ['ebs', 'staging'],
    linkedResource: 'Volúmenes staging',
    notifyOnFailure: true,
    command: 'aws ec2 create-snapshot --volume-ids batch',
    concurrency: 5,
  },
  {
    id: 'sch-16',
    name: 'Sync catálogo imágenes AMI',
    description: 'Importa AMIs aprobadas desde cuentas compartidas al catálogo interno.',
    type: 'sync',
    cron: '0 1 * * *',
    cronHuman: 'Todos los días a la 01:00',
    timezone: 'UTC',
    target: 'ami-catalog',
    owner: 'Plataforma',
    assignee: 'platform@cloudops.local',
    nextRun: 'Mañana 01:00',
    nextRunAt: ahead(300),
    lastRun: 'Hoy 01:02',
    lastRunAt: ago(600),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '12m',
    successRate: 95,
    runs7d: 7,
    failures7d: 0,
    tags: ['ami', 'catalog'],
    linkedResource: 'Catálogo AMI',
    notifyOnFailure: false,
    command: 'sync-ami-catalog --approved-only',
    concurrency: 1,
  },
  {
    id: 'sch-17',
    name: 'Escaneo vulnerabilidades contenedores',
    description: 'Trivy scan en registries ECR y reporte a Security Hub.',
    type: 'docker',
    cron: '0 4 * * *',
    cronHuman: 'Todos los días a las 04:00',
    timezone: 'UTC',
    target: 'ecr-*',
    owner: 'Seguridad',
    assignee: 'secops@cloudops.local',
    nextRun: 'Mañana 04:00',
    nextRunAt: ahead(480),
    lastRun: 'Hoy 04:22',
    lastRunAt: ago(480),
    lastResult: 'error',
    status: 'failed',
    enabled: true,
    retries: 2,
    maxDuration: '60m',
    successRate: 82,
    runs7d: 7,
    failures7d: 2,
    tags: ['trivy', 'security'],
    linkedResource: 'ECR org',
    notifyOnFailure: true,
    command: 'trivy image --severity HIGH,CRITICAL',
    parameters: 'REGISTRY=ecr',
    concurrency: 3,
  },
  {
    id: 'sch-18',
    name: 'Runbook reinicio servicio cache',
    description: 'Ejecuta runbook de rolling restart en cluster Redis cuando memoria > 85%.',
    type: 'runbook',
    cron: '15 */2 * * *',
    cronHuman: 'Cada 2 h (min 15)',
    timezone: 'Europe/Madrid',
    target: 'redis-cluster-prod',
    owner: 'Plataforma',
    assignee: 'scheduler@cloudops.local',
    nextRun: 'En 1 h 15 min',
    nextRunAt: ahead(75),
    lastRun: 'Hoy 12:15',
    lastRunAt: ago(45),
    lastResult: 'success',
    status: 'running',
    enabled: true,
    retries: 1,
    maxDuration: '20m',
    successRate: 96,
    runs7d: 84,
    failures7d: 1,
    tags: ['redis', 'runbook'],
    linkedResource: 'Runbook: Redis rolling restart',
    notifyOnFailure: true,
    command: 'runbook execute rb-redis-restart',
    parameters: 'THRESHOLD=85',
    concurrency: 1,
  },
]

export const defaultSchedulerHistory = (): SchedulerRunHistory[] => [
  {
    id: 'run-1',
    taskId: 'sch-6',
    taskName: 'Sync inventario GCP',
    type: 'sync',
    executedAt: ago(16),
    duration: '42s',
    result: 'success',
    triggeredBy: 'scheduler',
    output: '142 recursos actualizados · 0 conflictos',
  },
  {
    id: 'run-2',
    taskId: 'sch-5',
    taskName: 'Backup diario AWS RDS',
    type: 'backup',
    executedAt: ago(1320),
    duration: '11m 40s',
    result: 'success',
    triggeredBy: 'scheduler',
    output: 'Snapshot snap-0a8f2 · checksum OK',
  },
  {
    id: 'run-3',
    taskId: 'sch-3',
    taskName: 'Tests integración nocturnos',
    type: 'jenkins',
    executedAt: ago(1200),
    duration: '38m 12s',
    result: 'warning',
    triggeredBy: 'scheduler',
    output: 'Build #1841 UNSTABLE · 2 tests flaky',
  },
  {
    id: 'run-4',
    taskId: 'sch-8',
    taskName: 'Prune imágenes Docker',
    type: 'docker',
    executedAt: ago(10020),
    duration: '4m 02s',
    result: 'error',
    triggeredBy: 'scheduler',
    output: 'Host edge-02: permiso denegado en /var/lib/docker',
  },
  {
    id: 'run-5',
    taskId: 'sch-1',
    taskName: 'Apagar instancias staging',
    type: 'instance',
    executedAt: ago(1440),
    duration: '3m 18s',
    result: 'success',
    triggeredBy: 'scheduler',
    output: '12 instancias stopped · ahorro est. 18%',
  },
]
