/** Etiquetas de breadcrumb en español (ruta sin barra inicial). */
export const ROUTE_LABELS: Record<string, string> = {
  dashboard: 'Tablero',
  'command-center': 'Centro de mando',
  'resource-explorer': 'Explorador de recursos',
  'topology-map': 'Mapa de topología',
  'health-center': 'Centro de salud',
  'cloud/aws': 'AWS',
  'cloud/aws/overview': 'AWS — Resumen',
  'cloud/aws/accounts': 'AWS — Cuentas',
  'cloud/aws/instances': 'AWS — EC2',
  'cloud/aws/images': 'AWS — Imágenes',
  'cloud/aws/network': 'AWS — Red',
  'cloud/aws/billing': 'AWS — Facturación',
  'cloud/aws/metrics': 'AWS — Métricas',
  'cloud/gcp': 'GCP',
  'cloud/gcp/overview': 'GCP — Resumen',
  'cloud/gcp/accounts': 'GCP — Proyectos',
  'cloud/gcp/instances': 'GCP — Compute',
  'cloud/gcp/images': 'GCP — Imágenes',
  'cloud/gcp/network': 'GCP — Red',
  'cloud/gcp/billing': 'GCP — Facturación',
  'cloud/gcp/metrics': 'GCP — Métricas',
  'cloud/azure': 'Azure',
  'cloud/azure/overview': 'Azure — Resumen',
  'cloud/azure/accounts': 'Azure — Suscripciones',
  'cloud/azure/instances': 'Azure — Máquinas virtuales',
  'cloud/azure/images': 'Azure — Imágenes',
  'cloud/azure/network': 'Azure — Red',
  'cloud/azure/billing': 'Azure — Facturación',
  'cloud/azure/metrics': 'Azure — Métricas',
  'cloud/clouding': 'Clouding',
  'cloud/clouding/overview': 'Clouding — Resumen',
  'cloud/clouding/accounts': 'Clouding — Cuentas',
  'cloud/clouding/instances': 'Clouding — Instancias',
  'cloud/clouding/images': 'Clouding — Imágenes',
  'cloud/clouding/network': 'Clouding — Red',
  'cloud/clouding/billing': 'Clouding — Facturación',
  'cloud/clouding/metrics': 'Clouding — Métricas',
  'accounts/aws': 'AWS',
  'accounts/gcp': 'GCP',
  'accounts/azure': 'Azure',
  instances: 'Instancias',
  'instances/all-instances': 'Todas las instancias',
  vps: 'VPS / Bare metal',
  'vps/overview': 'VPS — Resumen',
  'vps/ionos': 'IONOS',
  'vps/ionos/overview': 'IONOS — Resumen',
  'vps/ionos/accounts': 'IONOS — Cuentas',
  'vps/ionos/servers': 'IONOS — Servidores',
  'vps/ionos/billing': 'IONOS — Facturación',
  'vps/ionos/metrics': 'IONOS — Métricas',
  'vps/vultr': 'Vultr',
  'vps/vultr/overview': 'Vultr — Resumen',
  'vps/vultr/accounts': 'Vultr — Cuentas',
  'vps/vultr/servers': 'Vultr — Servidores',
  'vps/vultr/billing': 'Vultr — Facturación',
  'vps/vultr/metrics': 'Vultr — Métricas',
  'vps/scaleway': 'Scaleway',
  'vps/scaleway/overview': 'Scaleway — Resumen',
  'vps/scaleway/accounts': 'Scaleway — Cuentas',
  'vps/scaleway/servers': 'Scaleway — Servidores',
  'vps/scaleway/billing': 'Scaleway — Facturación',
  'vps/scaleway/metrics': 'Scaleway — Métricas',
  docker: 'Docker',
  'docker/containers': 'Contenedores Docker',
  kubernetes: 'Kubernetes',
  'kubernetes/pods': 'Pods Kubernetes',
  network: 'Red',
  storage: 'Almacenamiento',
  backups: 'Copias de seguridad',
  'capacity-planner': 'Planificador de capacidad',
  repositories: 'Repositorios',
  'repositories/github': 'GitHub',
  'repositories/gitlab': 'GitLab',
  'repositories/webhooks': 'Webhooks',
  'repositories/branches': 'Ramas',
  'repositories/commits': 'Commits',
  'repositories/pull-requests': 'Pull Requests',
  'repositories/deployments': 'Despliegues',
  jenkins: 'Jenkins',
  'jenkins/jobs': 'Jobs Jenkins',
  'automation/ai-infra-studio': 'AI Infra Studio',
  'infra/ai-studio': 'AI Infra Studio',
  finops: 'FinOps',
  'finops/dashboard': 'Panel FinOps',
  'finops/billing': 'Facturación FinOps',
  'finops/instances': 'Instancias FinOps',
  'finops/cost-centers': 'Centros de coste',
  'finops/alerts': 'Alertas FinOps',
  'finops/recommendations': 'Insights IA',
  'finops/reports': 'Informes FinOps',
  'finops/settings': 'Configuración FinOps',
  deployments: 'Despliegues',
  terminal: 'Terminal',
  'terminal/active-sessions': 'Sesiones activas',
  'terminal/history': 'Historial',
  ssh: 'Terminal SSH',
  runbooks: 'Runbooks',
  'runbooks/executions': 'Ejecuciones',
  scheduler: 'Programador',
  'service-catalog': 'Catálogo de servicios',
  approvals: 'Aprobaciones',
  metrics: 'Métricas',
  'metrics/overview': 'Métricas — Resumen',
  logs: 'Logs',
  billing: 'Facturación',
  'billing/overview': 'Facturación — Resumen',
  'cost-optimizer': 'Optimizador de costes',
  alerts: 'Alertas',
  'alerts/active': 'Alertas activas',
  incidents: 'Incidentes',
  notifications: 'Notificaciones',
  'notifications/all': 'Todas las notificaciones',
  reports: 'Informes',
  'change-management': 'Gestión de cambios',
  'security-center': 'Centro de seguridad',
  'secrets-manager': 'Gestor de secretos',
  compliance: 'Cumplimiento / Políticas',
  'access-control': 'Control de acceso',
  audit: 'Auditoría',
  'audit/activity-logs': 'Registro de actividad',
  'audit/security-events': 'Eventos de seguridad',
  'audit/compliance-trail': 'Trail de cumplimiento',
  'audit/exports': 'Exportaciones',
  'admin/users': 'Usuarios',
  'admin/roles': 'Roles',
  'admin/api-tokens': 'Tokens API',
  'admin/webhooks': 'Webhooks',
  settings: 'Configuración',
  'settings/general': 'Configuración general',
  'settings/copilot': 'Copilot IA',
  'ai-assistant': 'Asistente IA',
}

export const resolveRouteLabel = (url: string): string => {
  const path = url.replace(/^\//, '').split('?')[0]
  if (ROUTE_LABELS[path]) return ROUTE_LABELS[path]

  const segments = path.split('/')
  for (let len = segments.length; len > 0; len--) {
    const key = segments.slice(0, len).join('/')
    if (ROUTE_LABELS[key]) return ROUTE_LABELS[key]
  }

  const last = segments[segments.length - 1] ?? 'Página'
  return last.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
