/** Breadcrumb labels keyed by route path (without leading slash). */
export const ROUTE_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  'command-center': 'Command Center',
  'resource-explorer': 'Resource Explorer',
  'topology-map': 'Topology Map',
  'health-center': 'Health Center',
  'cloud/aws': 'AWS',
  'cloud/aws/overview': 'AWS Overview',
  'cloud/aws/accounts': 'AWS Accounts',
  'cloud/aws/instances': 'AWS EC2',
  'cloud/aws/network': 'AWS Network',
  'cloud/aws/billing': 'AWS Billing',
  'cloud/aws/metrics': 'AWS Metrics',
  'cloud/gcp': 'GCP',
  'cloud/gcp/overview': 'GCP Overview',
  'cloud/gcp/accounts': 'GCP Projects',
  'cloud/gcp/instances': 'GCP Compute',
  'cloud/gcp/network': 'GCP Network',
  'cloud/gcp/billing': 'GCP Billing',
  'cloud/gcp/metrics': 'GCP Metrics',
  'cloud/azure': 'Azure',
  'cloud/azure/overview': 'Azure Overview',
  'cloud/azure/accounts': 'Azure Subscriptions',
  'cloud/azure/instances': 'Azure VMs',
  'cloud/azure/network': 'Azure Network',
  'cloud/azure/billing': 'Azure Billing',
  'cloud/azure/metrics': 'Azure Metrics',
  'accounts/aws': 'AWS',
  'accounts/gcp': 'GCP',
  'accounts/azure': 'Azure',
  instances: 'Instances',
  'instances/all-instances': 'All Instances',
  vps: 'VPS / Bare Metal',
  'vps/overview': 'VPS Overview',
  docker: 'Docker',
  'docker/containers': 'Docker Containers',
  kubernetes: 'Kubernetes',
  'kubernetes/pods': 'Kubernetes Pods',
  network: 'Network',
  storage: 'Storage',
  backups: 'Backups',
  'capacity-planner': 'Capacity Planner',
  jenkins: 'Jenkins',
  'jenkins/jobs': 'Jenkins Jobs',
  terraform: 'Terraform',
  'terraform/workspaces': 'Terraform Workspaces',
  deployments: 'Deployments',
  terminal: 'Terminal',
  'terminal/active-sessions': 'Active Sessions',
  ssh: 'SSH Terminal',
  runbooks: 'Runbooks',
  scheduler: 'Scheduler',
  'service-catalog': 'Service Catalog',
  approvals: 'Approvals',
  metrics: 'Metrics',
  'metrics/overview': 'Metrics Overview',
  logs: 'Logs',
  billing: 'Billing',
  'billing/overview': 'Billing Overview',
  'cost-optimizer': 'Cost Optimizer',
  alerts: 'Alerts',
  'alerts/active': 'Active Alerts',
  incidents: 'Incidents',
  notifications: 'Notifications',
  'notifications/all': 'All Notifications',
  reports: 'Reports',
  'change-management': 'Change Management',
  'security-center': 'Security Center',
  'secrets-manager': 'Secrets Manager',
  compliance: 'Compliance',
  'access-control': 'Access Control',
  audit: 'Audit',
  'audit/activity-logs': 'Activity Logs',
  'admin/users': 'Users',
  'admin/roles': 'Roles',
  'admin/api-tokens': 'API Tokens',
  'admin/webhooks': 'Webhooks',
  'admin/demo-mode': 'Demo Mode',
  settings: 'Settings',
  'settings/general': 'General Settings',
  'ai-assistant': 'AI Assistant',
}

export const resolveRouteLabel = (url: string): string => {
  const path = url.replace(/^\//, '').split('?')[0]
  if (ROUTE_LABELS[path]) return ROUTE_LABELS[path]

  const segments = path.split('/')
  for (let len = segments.length; len > 0; len--) {
    const key = segments.slice(0, len).join('/')
    if (ROUTE_LABELS[key]) return ROUTE_LABELS[key]
  }

  const last = segments[segments.length - 1] ?? 'Page'
  return last.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
